import {Speaker, Transcript, Word} from "./models";

const SPEAKERS: Speaker[] = [
  { id: 0, name: "Flavius" },
  { id: 1, name: "Carpenter" },
  { id: 2, name: "Marcellus" },
  { id: 3, name: "Cobbler" }
]

export const FULL_TEXT: string =
  "Hence! Home, you idle creatures, get you home! Is this a holiday? What, know you not, being mechanical, " +
  "you ought not walk upon a laboring day without the sign of your profession? Speak, what trade art thou? " +
  "Why, sir, a carpenter. Where is thy leather apron and thy rule? What dost thou with thy best apparel on? " +
  "You, sir, what trade are you? Truly, sir, in respect of a fine workman, I am but, as you would say, " +
  "a cobbler. But what trade art thou? Answer me directly. A trade, sir, that I hope I may use with a safe " +
  "conscience, which is indeed, sir, a mender of bad soles. What trade, thou knave? Thou naughty knave, " +
  "what trade? Nay, I beseech you, sir, be not out with me. Yet if you be out, sir, I can mend you. What " +
  "mean’st thou by that? Mend me, thou saucy fellow? Why, sir, cobble you. Thou art a cobbler, art thou? " +
  "Truly, sir, all that I live by is with the awl. I meddle with no tradesman’s matters nor women’s " +
  "matters, but withal I am indeed, sir, a surgeon to old shoes: when they are in great danger, I recover " +
  "them. As proper men as ever trod upon neat’s leather have gone upon my handiwork. But wherefore art not " +
  "in thy shop today? Why dost thou lead these men about the streets? Truly, sir, to wear out their shoes, " +
  "to get myself into more work. But indeed, sir, we make holiday to see Caesar and to rejoice in his triumph.";

export const WORDS: Word[] = [
  {
    "value": "Hence",
    "speaker": 0,
    "startTime": 0,
    "endTime": 1
  }, {
    "value": "Home",
    "speaker": 0,
    "startTime": 1,
    "endTime": 2
  }, {
    "value": "you",
    "speaker": 0,
    "startTime": 2,
    "endTime": 3
  }, {
    "value": "idle",
    "speaker": 0,
    "startTime": 3,
    "endTime": 4
  }, {
    "value": "creatures",
    "speaker": 0,
    "startTime": 4,
    "endTime": 5
  }, {
    "value": "get",
    "speaker": 0,
    "startTime": 5,
    "endTime": 6
  }, {
    "value": "you",
    "speaker": 0,
    "startTime": 6,
    "endTime": 7
  }, {
    "value": "home",
    "speaker": 0,
    "startTime": 7,
    "endTime": 8
  }, {
    "value": "Is",
    "speaker": 0,
    "startTime": 8,
    "endTime": 9
  }, {
    "value": "this",
    "speaker": 0,
    "startTime": 9,
    "endTime": 10
  }, {
    "value": "a",
    "speaker": 0,
    "startTime": 10,
    "endTime": 11
  }, {
    "value": "holiday",
    "speaker": 0,
    "startTime": 11,
    "endTime": 12
  }, {
    "value": "What",
    "speaker": 0,
    "startTime": 12,
    "endTime": 13
  }, {
    "value": "know",
    "speaker": 0,
    "startTime": 13,
    "endTime": 14
  }, {
    "value": "you",
    "speaker": 0,
    "startTime": 14,
    "endTime": 15
  }, {
    "value": "not",
    "speaker": 0,
    "startTime": 15,
    "endTime": 16
  }, {
    "value": "being",
    "speaker": 0,
    "startTime": 16,
    "endTime": 17
  }, {
    "value": "mechanical",
    "speaker": 0,
    "startTime": 17,
    "endTime": 18
  }, {
    "value": "you",
    "speaker": 0,
    "startTime": 18,
    "endTime": 19
  }, {
    "value": "ought",
    "speaker": 0,
    "startTime": 19,
    "endTime": 20
  }, {
    "value": "not",
    "speaker": 0,
    "startTime": 20,
    "endTime": 21
  }, {
    "value": "walk",
    "speaker": 0,
    "startTime": 21,
    "endTime": 22
  }, {
    "value": "upon",
    "speaker": 0,
    "startTime": 22,
    "endTime": 23
  }, {
    "value": "a",
    "speaker": 0,
    "startTime": 23,
    "endTime": 24
  }, {
    "value": "laboring",
    "speaker": 0,
    "startTime": 24,
    "endTime": 25
  }, {
    "value": "day",
    "speaker": 0,
    "startTime": 25,
    "endTime": 26
  }, {
    "value": "without",
    "speaker": 0,
    "startTime": 26,
    "endTime": 27
  }, {
    "value": "the",
    "speaker": 0,
    "startTime": 27,
    "endTime": 28
  }, {
    "value": "sign",
    "speaker": 0,
    "startTime": 28,
    "endTime": 29
  }, {
    "value": "of",
    "speaker": 0,
    "startTime": 29,
    "endTime": 30
  }, {
    "value": "your",
    "speaker": 0,
    "startTime": 30,
    "endTime": 31
  }, {
    "value": "profession",
    "speaker": 0,
    "startTime": 31,
    "endTime": 32
  }, {
    "value": "Speak",
    "speaker": 0,
    "startTime": 32,
    "endTime": 33
  }, {
    "value": "what",
    "speaker": 0,
    "startTime": 33,
    "endTime": 34
  }, {
    "value": "trade",
    "speaker": 0,
    "startTime": 34,
    "endTime": 35
  }, {
    "value": "art",
    "speaker": 0,
    "startTime": 35,
    "endTime": 36
  }, {
    "value": "thou",
    "speaker": 0,
    "startTime": 36,
    "endTime": 37
  },{
    "value": "Why",
    "speaker": 1,
    "startTime": 37,
    "endTime": 38
  }, {
    "value": "sir",
    "speaker": 1,
    "startTime": 38,
    "endTime": 39
  }, {
    "value": "a",
    "speaker": 1,
    "startTime": 39,
    "endTime": 40
  }, {
    "value": "carpenter",
    "speaker": 1,
    "startTime": 40,
    "endTime": 41
  },{
    "value": "Where",
    "speaker": 2,
    "startTime": 41,
    "endTime": 42
  }, {
    "value": "is",
    "speaker": 2,
    "startTime": 42,
    "endTime": 43
  }, {
    "value": "thy",
    "speaker": 2,
    "startTime": 43,
    "endTime": 44
  }, {
    "value": "leather",
    "speaker": 2,
    "startTime": 44,
    "endTime": 45
  }, {
    "value": "apron",
    "speaker": 2,
    "startTime": 45,
    "endTime": 46
  }, {
    "value": "and",
    "speaker": 2,
    "startTime": 46,
    "endTime": 47
  }, {
    "value": "thy",
    "speaker": 2,
    "startTime": 47,
    "endTime": 48
  }, {
    "value": "rule",
    "speaker": 2,
    "startTime": 48,
    "endTime": 49
  }, {
    "value": "What",
    "speaker": 2,
    "startTime": 49,
    "endTime": 50
  }, {
    "value": "dost",
    "speaker": 2,
    "startTime": 50,
    "endTime": 51
  }, {
    "value": "thou",
    "speaker": 2,
    "startTime": 51,
    "endTime": 52
  }, {
    "value": "with",
    "speaker": 2,
    "startTime": 52,
    "endTime": 53
  }, {
    "value": "thy",
    "speaker": 2,
    "startTime": 53,
    "endTime": 54
  }, {
    "value": "best",
    "speaker": 2,
    "startTime": 54,
    "endTime": 55
  }, {
    "value": "apparel",
    "speaker": 2,
    "startTime": 55,
    "endTime": 56
  }, {
    "value": "on",
    "speaker": 2,
    "startTime": 56,
    "endTime": 57
  }, {
    "value": "You",
    "speaker": 2,
    "startTime": 57,
    "endTime": 58
  }, {
    "value": "sir",
    "speaker": 2,
    "startTime": 58,
    "endTime": 59
  }, {
    "value": "what",
    "speaker": 2,
    "startTime": 59,
    "endTime": 60
  }, {
    "value": "trade",
    "speaker": 2,
    "startTime": 60,
    "endTime": 61
  }, {
    "value": "are",
    "speaker": 2,
    "startTime": 61,
    "endTime": 62
  }, {
    "value": "you",
    "speaker": 2,
    "startTime": 62,
    "endTime": 63
  },{
    "value": "Truly",
    "speaker": 3,
    "startTime": 63,
    "endTime": 64
  }, {
    "value": "sir",
    "speaker": 3,
    "startTime": 64,
    "endTime": 65
  }, {
    "value": "in",
    "speaker": 3,
    "startTime": 65,
    "endTime": 66
  }, {
    "value": "respect",
    "speaker": 3,
    "startTime": 66,
    "endTime": 67
  }, {
    "value": "of",
    "speaker": 3,
    "startTime": 67,
    "endTime": 68
  }, {
    "value": "a",
    "speaker": 3,
    "startTime": 68,
    "endTime": 69
  }, {
    "value": "fine",
    "speaker": 3,
    "startTime": 69,
    "endTime": 70
  }, {
    "value": "workman",
    "speaker": 3,
    "startTime": 70,
    "endTime": 71
  }, {
    "value": "I",
    "speaker": 3,
    "startTime": 71,
    "endTime": 72
  }, {
    "value": "am",
    "speaker": 3,
    "startTime": 72,
    "endTime": 73
  }, {
    "value": "but",
    "speaker": 3,
    "startTime": 73,
    "endTime": 74
  }, {
    "value": "as",
    "speaker": 3,
    "startTime": 74,
    "endTime": 75
  }, {
    "value": "you",
    "speaker": 3,
    "startTime": 75,
    "endTime": 76
  }, {
    "value": "would",
    "speaker": 3,
    "startTime": 76,
    "endTime": 77
  }, {
    "value": "say",
    "speaker": 3,
    "startTime": 77,
    "endTime": 78
  }, {
    "value": "a",
    "speaker": 3,
    "startTime": 78,
    "endTime": 79
  }, {
    "value": "cobbler",
    "speaker": 3,
    "startTime": 79,
    "endTime": 80
  },{
    "value": "But",
    "speaker": 2,
    "startTime": 80,
    "endTime": 81
  }, {
    "value": "what",
    "speaker": 2,
    "startTime": 81,
    "endTime": 82
  }, {
    "value": "trade",
    "speaker": 2,
    "startTime": 82,
    "endTime": 83
  }, {
    "value": "art",
    "speaker": 2,
    "startTime": 83,
    "endTime": 84
  }, {
    "value": "thou",
    "speaker": 2,
    "startTime": 84,
    "endTime": 85
  }, {
    "value": "Answer",
    "speaker": 2,
    "startTime": 85,
    "endTime": 86
  }, {
    "value": "me",
    "speaker": 2,
    "startTime": 86,
    "endTime": 87
  }, {
    "value": "directly",
    "speaker": 2,
    "startTime": 87,
    "endTime": 88
  },{
    "value": "A",
    "speaker": 3,
    "startTime": 88,
    "endTime": 89
  }, {
    "value": "trade",
    "speaker": 3,
    "startTime": 89,
    "endTime": 90
  }, {
    "value": "sir",
    "speaker": 3,
    "startTime": 90,
    "endTime": 91
  }, {
    "value": "that",
    "speaker": 3,
    "startTime": 91,
    "endTime": 92
  }, {
    "value": "I",
    "speaker": 3,
    "startTime": 92,
    "endTime": 93
  }, {
    "value": "hope",
    "speaker": 3,
    "startTime": 93,
    "endTime": 94
  }, {
    "value": "I",
    "speaker": 3,
    "startTime": 94,
    "endTime": 95
  }, {
    "value": "may",
    "speaker": 3,
    "startTime": 95,
    "endTime": 96
  }, {
    "value": "use",
    "speaker": 3,
    "startTime": 96,
    "endTime": 97
  }, {
    "value": "with",
    "speaker": 3,
    "startTime": 97,
    "endTime": 98
  }, {
    "value": "a",
    "speaker": 3,
    "startTime": 98,
    "endTime": 99
  }, {
    "value": "safe",
    "speaker": 3,
    "startTime": 99,
    "endTime": 100
  }, {
    "value": "conscience",
    "speaker": 3,
    "startTime": 100,
    "endTime": 101
  }, {
    "value": "which",
    "speaker": 3,
    "startTime": 101,
    "endTime": 102
  }, {
    "value": "is",
    "speaker": 3,
    "startTime": 102,
    "endTime": 103
  }, {
    "value": "indeed",
    "speaker": 3,
    "startTime": 103,
    "endTime": 104
  }, {
    "value": "sir",
    "speaker": 3,
    "startTime": 104,
    "endTime": 105
  }, {
    "value": "a",
    "speaker": 3,
    "startTime": 105,
    "endTime": 106
  }, {
    "value": "mender",
    "speaker": 3,
    "startTime": 106,
    "endTime": 107
  }, {
    "value": "of",
    "speaker": 3,
    "startTime": 107,
    "endTime": 108
  }, {
    "value": "bad",
    "speaker": 3,
    "startTime": 108,
    "endTime": 109
  }, {
    "value": "soles",
    "speaker": 3,
    "startTime": 109,
    "endTime": 110
  },{
    "value": "What",
    "speaker": 0,
    "startTime": 110,
    "endTime": 111
  }, {
    "value": "trade",
    "speaker": 0,
    "startTime": 111,
    "endTime": 112
  }, {
    "value": "thou",
    "speaker": 0,
    "startTime": 112,
    "endTime": 113
  }, {
    "value": "knave",
    "speaker": 0,
    "startTime": 113,
    "endTime": 114
  }, {
    "value": "Thou",
    "speaker": 0,
    "startTime": 114,
    "endTime": 115
  }, {
    "value": "naughty",
    "speaker": 0,
    "startTime": 115,
    "endTime": 116
  }, {
    "value": "knave",
    "speaker": 0,
    "startTime": 116,
    "endTime": 117
  }, {
    "value": "what",
    "speaker": 0,
    "startTime": 117,
    "endTime": 118
  }, {
    "value": "trade",
    "speaker": 0,
    "startTime": 118,
    "endTime": 119
  },{
    "value": "Nay",
    "speaker": 3,
    "startTime": 119,
    "endTime": 120
  }, {
    "value": "I",
    "speaker": 3,
    "startTime": 120,
    "endTime": 121
  }, {
    "value": "beseech",
    "speaker": 3,
    "startTime": 121,
    "endTime": 122
  }, {
    "value": "you",
    "speaker": 3,
    "startTime": 122,
    "endTime": 123
  }, {
    "value": "sir",
    "speaker": 3,
    "startTime": 123,
    "endTime": 124
  }, {
    "value": "be",
    "speaker": 3,
    "startTime": 124,
    "endTime": 125
  }, {
    "value": "not",
    "speaker": 3,
    "startTime": 125,
    "endTime": 126
  }, {
    "value": "out",
    "speaker": 3,
    "startTime": 126,
    "endTime": 127
  }, {
    "value": "with",
    "speaker": 3,
    "startTime": 127,
    "endTime": 128
  }, {
    "value": "me",
    "speaker": 3,
    "startTime": 128,
    "endTime": 129
  }, {
    "value": "Yet",
    "speaker": 3,
    "startTime": 129,
    "endTime": 130
  }, {
    "value": "if",
    "speaker": 3,
    "startTime": 130,
    "endTime": 131
  }, {
    "value": "you",
    "speaker": 3,
    "startTime": 131,
    "endTime": 132
  }, {
    "value": "be",
    "speaker": 3,
    "startTime": 132,
    "endTime": 133
  }, {
    "value": "out",
    "speaker": 3,
    "startTime": 133,
    "endTime": 134
  }, {
    "value": "sir",
    "speaker": 3,
    "startTime": 134,
    "endTime": 135
  }, {
    "value": "I",
    "speaker": 3,
    "startTime": 135,
    "endTime": 136
  }, {
    "value": "can",
    "speaker": 3,
    "startTime": 136,
    "endTime": 137
  }, {
    "value": "mend",
    "speaker": 3,
    "startTime": 137,
    "endTime": 138
  }, {
    "value": "you",
    "speaker": 3,
    "startTime": 138,
    "endTime": 139
  },{
    "value": "What",
    "speaker": 2,
    "startTime": 139,
    "endTime": 140
  }, {
    "value": "mean'st",
    "speaker": 2,
    "startTime": 140,
    "endTime": 141
  }, {
    "value": "thou",
    "speaker": 2,
    "startTime": 141,
    "endTime": 142
  }, {
    "value": "by",
    "speaker": 2,
    "startTime": 142,
    "endTime": 143
  }, {
    "value": "that",
    "speaker": 2,
    "startTime": 143,
    "endTime": 144
  }, {
    "value": "Mend",
    "speaker": 2,
    "startTime": 144,
    "endTime": 145
  }, {
    "value": "me",
    "speaker": 2,
    "startTime": 145,
    "endTime": 146
  }, {
    "value": "thou",
    "speaker": 2,
    "startTime": 146,
    "endTime": 147
  }, {
    "value": "saucy",
    "speaker": 2,
    "startTime": 147,
    "endTime": 148
  }, {
    "value": "fellow",
    "speaker": 2,
    "startTime": 148,
    "endTime": 149
  },{
    "value": "Why",
    "speaker": 3,
    "startTime": 149,
    "endTime": 150
  }, {
    "value": "sir",
    "speaker": 3,
    "startTime": 150,
    "endTime": 151
  }, {
    "value": "cobble",
    "speaker": 3,
    "startTime": 151,
    "endTime": 152
  }, {
    "value": "you",
    "speaker": 3,
    "startTime": 152,
    "endTime": 153
  },{
    "value": "Thou",
    "speaker": 0,
    "startTime": 153,
    "endTime": 154
  }, {
    "value": "art",
    "speaker": 0,
    "startTime": 154,
    "endTime": 155
  }, {
    "value": "a",
    "speaker": 0,
    "startTime": 155,
    "endTime": 156
  }, {
    "value": "cobbler",
    "speaker": 0,
    "startTime": 156,
    "endTime": 157
  }, {
    "value": "art",
    "speaker": 0,
    "startTime": 157,
    "endTime": 158
  }, {
    "value": "thou",
    "speaker": 0,
    "startTime": 158,
    "endTime": 159
  },{
    "value": "Truly",
    "speaker": 3,
    "startTime": 159,
    "endTime": 160
  }, {
    "value": "sir",
    "speaker": 3,
    "startTime": 160,
    "endTime": 161
  }, {
    "value": "all",
    "speaker": 3,
    "startTime": 161,
    "endTime": 162
  }, {
    "value": "that",
    "speaker": 3,
    "startTime": 162,
    "endTime": 163
  }, {
    "value": "I",
    "speaker": 3,
    "startTime": 163,
    "endTime": 164
  }, {
    "value": "live",
    "speaker": 3,
    "startTime": 164,
    "endTime": 165
  }, {
    "value": "by",
    "speaker": 3,
    "startTime": 165,
    "endTime": 166
  }, {
    "value": "is",
    "speaker": 3,
    "startTime": 166,
    "endTime": 167
  }, {
    "value": "with",
    "speaker": 3,
    "startTime": 167,
    "endTime": 168
  }, {
    "value": "the",
    "speaker": 3,
    "startTime": 168,
    "endTime": 169
  }, {
    "value": "awl",
    "speaker": 3,
    "startTime": 169,
    "endTime": 170
  }, {
    "value": "I",
    "speaker": 3,
    "startTime": 170,
    "endTime": 171
  }, {
    "value": "meddle",
    "speaker": 3,
    "startTime": 171,
    "endTime": 172
  }, {
    "value": "with",
    "speaker": 3,
    "startTime": 172,
    "endTime": 173
  }, {
    "value": "no",
    "speaker": 3,
    "startTime": 173,
    "endTime": 174
  }, {
    "value": "tradesman's",
    "speaker": 3,
    "startTime": 174,
    "endTime": 175
  }, {
    "value": "matters",
    "speaker": 3,
    "startTime": 175,
    "endTime": 176
  }, {
    "value": "nor",
    "speaker": 3,
    "startTime": 176,
    "endTime": 177
  }, {
    "value": "women's",
    "speaker": 3,
    "startTime": 177,
    "endTime": 178
  }, {
    "value": "matters",
    "speaker": 3,
    "startTime": 178,
    "endTime": 179
  }, {
    "value": "but",
    "speaker": 3,
    "startTime": 179,
    "endTime": 180
  }, {
    "value": "withal",
    "speaker": 3,
    "startTime": 180,
    "endTime": 181
  }, {
    "value": "I",
    "speaker": 3,
    "startTime": 181,
    "endTime": 182
  }, {
    "value": "am",
    "speaker": 3,
    "startTime": 182,
    "endTime": 183
  }, {
    "value": "indeed",
    "speaker": 3,
    "startTime": 183,
    "endTime": 184
  }, {
    "value": "sir",
    "speaker": 3,
    "startTime": 184,
    "endTime": 185
  }, {
    "value": "a",
    "speaker": 3,
    "startTime": 185,
    "endTime": 186
  }, {
    "value": "surgeon",
    "speaker": 3,
    "startTime": 186,
    "endTime": 187
  }, {
    "value": "to",
    "speaker": 3,
    "startTime": 187,
    "endTime": 188
  }, {
    "value": "old",
    "speaker": 3,
    "startTime": 188,
    "endTime": 189
  }, {
    "value": "shoes:",
    "speaker": 3,
    "startTime": 189,
    "endTime": 190
  }, {
    "value": "when",
    "speaker": 3,
    "startTime": 190,
    "endTime": 191
  }, {
    "value": "they",
    "speaker": 3,
    "startTime": 191,
    "endTime": 192
  }, {
    "value": "are",
    "speaker": 3,
    "startTime": 192,
    "endTime": 193
  }, {
    "value": "in",
    "speaker": 3,
    "startTime": 193,
    "endTime": 194
  }, {
    "value": "great",
    "speaker": 3,
    "startTime": 194,
    "endTime": 195
  }, {
    "value": "danger",
    "speaker": 3,
    "startTime": 195,
    "endTime": 196
  }, {
    "value": "I",
    "speaker": 3,
    "startTime": 196,
    "endTime": 197
  }, {
    "value": "recover",
    "speaker": 3,
    "startTime": 197,
    "endTime": 198
  }, {
    "value": "them",
    "speaker": 3,
    "startTime": 198,
    "endTime": 199
  }, {
    "value": "As",
    "speaker": 3,
    "startTime": 199,
    "endTime": 200
  }, {
    "value": "proper",
    "speaker": 3,
    "startTime": 200,
    "endTime": 201
  }, {
    "value": "men",
    "speaker": 3,
    "startTime": 201,
    "endTime": 202
  }, {
    "value": "as",
    "speaker": 3,
    "startTime": 202,
    "endTime": 203
  }, {
    "value": "ever",
    "speaker": 3,
    "startTime": 203,
    "endTime": 204
  }, {
    "value": "trod",
    "speaker": 3,
    "startTime": 204,
    "endTime": 205
  }, {
    "value": "upon",
    "speaker": 3,
    "startTime": 205,
    "endTime": 206
  }, {
    "value": "neat's",
    "speaker": 3,
    "startTime": 206,
    "endTime": 207
  }, {
    "value": "leather",
    "speaker": 3,
    "startTime": 207,
    "endTime": 208
  }, {
    "value": "have",
    "speaker": 3,
    "startTime": 208,
    "endTime": 209
  }, {
    "value": "gone",
    "speaker": 3,
    "startTime": 209,
    "endTime": 210
  }, {
    "value": "upon",
    "speaker": 3,
    "startTime": 210,
    "endTime": 211
  }, {
    "value": "my",
    "speaker": 3,
    "startTime": 211,
    "endTime": 212
  }, {
    "value": "handiwork",
    "speaker": 3,
    "startTime": 212,
    "endTime": 213
  },{
    "value": "But",
    "speaker": 0,
    "startTime": 213,
    "endTime": 214
  }, {
    "value": "wherefore",
    "speaker": 0,
    "startTime": 214,
    "endTime": 215
  }, {
    "value": "art",
    "speaker": 0,
    "startTime": 215,
    "endTime": 216
  }, {
    "value": "not",
    "speaker": 0,
    "startTime": 216,
    "endTime": 217
  }, {
    "value": "in",
    "speaker": 0,
    "startTime": 217,
    "endTime": 218
  }, {
    "value": "thy",
    "speaker": 0,
    "startTime": 218,
    "endTime": 219
  }, {
    "value": "shop",
    "speaker": 0,
    "startTime": 219,
    "endTime": 220
  }, {
    "value": "today",
    "speaker": 0,
    "startTime": 220,
    "endTime": 221
  }, {
    "value": "Why",
    "speaker": 0,
    "startTime": 221,
    "endTime": 222
  }, {
    "value": "dost",
    "speaker": 0,
    "startTime": 222,
    "endTime": 223
  }, {
    "value": "thou",
    "speaker": 0,
    "startTime": 223,
    "endTime": 224
  }, {
    "value": "lead",
    "speaker": 0,
    "startTime": 224,
    "endTime": 225
  }, {
    "value": "these",
    "speaker": 0,
    "startTime": 225,
    "endTime": 226
  }, {
    "value": "men",
    "speaker": 0,
    "startTime": 226,
    "endTime": 227
  }, {
    "value": "about",
    "speaker": 0,
    "startTime": 227,
    "endTime": 228
  }, {
    "value": "the",
    "speaker": 0,
    "startTime": 228,
    "endTime": 229
  }, {
    "value": "streets",
    "speaker": 0,
    "startTime": 229,
    "endTime": 230
  },{
    "value": "Truly",
    "speaker": 3,
    "startTime": 230,
    "endTime": 231
  }, {
    "value": "sir",
    "speaker": 3,
    "startTime": 231,
    "endTime": 232
  }, {
    "value": "to",
    "speaker": 3,
    "startTime": 232,
    "endTime": 233
  }, {
    "value": "wear",
    "speaker": 3,
    "startTime": 233,
    "endTime": 234
  }, {
    "value": "out",
    "speaker": 3,
    "startTime": 234,
    "endTime": 235
  }, {
    "value": "their",
    "speaker": 3,
    "startTime": 235,
    "endTime": 236
  }, {
    "value": "shoes",
    "speaker": 3,
    "startTime": 236,
    "endTime": 237
  }, {
    "value": "to",
    "speaker": 3,
    "startTime": 237,
    "endTime": 238
  }, {
    "value": "get",
    "speaker": 3,
    "startTime": 238,
    "endTime": 239
  }, {
    "value": "myself",
    "speaker": 3,
    "startTime": 239,
    "endTime": 240
  }, {
    "value": "into",
    "speaker": 3,
    "startTime": 240,
    "endTime": 241
  }, {
    "value": "more",
    "speaker": 3,
    "startTime": 241,
    "endTime": 242
  }, {
    "value": "work",
    "speaker": 3,
    "startTime": 242,
    "endTime": 243
  }, {
    "value": "But",
    "speaker": 3,
    "startTime": 243,
    "endTime": 244
  }, {
    "value": "indeed",
    "speaker": 3,
    "startTime": 244,
    "endTime": 245
  }, {
    "value": "sir",
    "speaker": 3,
    "startTime": 245,
    "endTime": 246
  }, {
    "value": "we",
    "speaker": 3,
    "startTime": 246,
    "endTime": 247
  }, {
    "value": "make",
    "speaker": 3,
    "startTime": 247,
    "endTime": 248
  }, {
    "value": "holiday",
    "speaker": 3,
    "startTime": 248,
    "endTime": 249
  }, {
    "value": "to",
    "speaker": 3,
    "startTime": 249,
    "endTime": 250
  }, {
    "value": "see",
    "speaker": 3,
    "startTime": 250,
    "endTime": 251
  }, {
    "value": "Caesar",
    "speaker": 3,
    "startTime": 251,
    "endTime": 252
  }, {
    "value": "and",
    "speaker": 3,
    "startTime": 252,
    "endTime": 253
  }, {
    "value": "to",
    "speaker": 3,
    "startTime": 253,
    "endTime": 254
  }, {
    "value": "rejoice",
    "speaker": 3,
    "startTime": 254,
    "endTime": 255
  }, {
    "value": "in",
    "speaker": 3,
    "startTime": 255,
    "endTime": 256
  }, {
    "value": "his",
    "speaker": 3,
    "startTime": 256,
    "endTime": 257
  }, {
    "value": "triumph",
    "speaker": 3,
    "startTime": 257,
    "endTime": 258
  }
]

export const TRANSCRIPT: Transcript = {
  videoUrl: "https://www.youtube.com/watch?v=mQQh115qAME",
  speakers: SPEAKERS,
  fullText: FULL_TEXT,
  words: WORDS,
}
